# suppress inspection "UnusedProperty" for whole file
displayName=Dude, Where's My Stuff?
author=Thource
description=Find your stuff with ease.
tags=uim,storage,deathbank,deathstorage,death,deathpile,coins,poh,stash,minigames,leprechaun,fossils
plugins=dev.thource.runelite.dudewheresmystuff.DudeWheresMyStuffPlugin
build=gradle
