/*
 * Copyright (c) 2018, Tomas Slusny <slusnucky@gmail.com>
 * Copyright (c) 2018, PandahRS <https://github.com/PandahRS>
 * Copyright (c) 2020, Brooklyn <https://github.com/Broooklyn>
 * Copyright (c) 2022, Thource <https://github.com/Thource>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package dev.thource.runelite.dudewheresmystuff;

import com.google.common.collect.ImmutableMap;
import com.google.gson.Gson;
import java.util.Map;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Region serves as a way to get a descriptive name of a WorldLocation.
 *
 * <p>The data for each region is loaded from {@code data/RegionData.json}, which is generated from
 * {@code RegionData} in the test source set by {@code EnumJsonGenerator}. Do not edit the JSON by
 * hand.
 *
 * <p>Call {@link #load(Gson)} with the plugin's injected Gson before using {@link #get(int)} or any
 * of the getters.
 */
public enum Region {
  BOSS_ABYSSAL_SIRE,
  BOSS_ARAXXOR,
  BOSS_CERBERUS,
  BOSS_COMMANDER_ZILYANA,
  BOSS_CORP,
  BOSS_DKS,
  BOSS_DUKE_SUCELLUS,
  BOSS_DOOM,
  BOSS_GENERAL_GRAARDOR,
  BOSS_GIANT_MOLE,
  BOSS_GROTESQUE_GUARDIANS,
  BOSS_HESPORI,
  BOSS_HYDRA,
  BOSS_KQ,
  BOSS_KRAKEN,
  BOSS_KREEARRA,
  BOSS_KRIL_TSUTSAROTH,
  BOSS_NEX,
  BOSS_NIGHTMARE,
  BOSS_PHANTOM_MUSPAH,
  BOSS_SARACHNIS,
  BOSS_SKOTIZO,
  BOSS_SMOKE_DEVIL,
  BOSS_TEMPOROSS,
  BOSS_THE_LEVIATHAN,
  BOSS_THE_ROYAL_TITANS,
  BOSS_THE_WHISPERER,
  BOSS_VARDORVIS,
  BOSS_VORKATH,
  BOSS_WINTERTODT,
  BOSS_YAMA,
  BOSS_ZALCANO,
  BOSS_ZULRAH,
  CITY_AL_KHARID,
  CITY_ARCEUUS_HOUSE,
  CITY_ARDOUGNE,
  CITY_BANDIT_CAMP,
  CITY_BARBARIAN_OUTPOST,
  CITY_BARBARIAN_VILLAGE,
  CITY_BEDABIN_CAMP,
  CITY_BRIMHAVEN,
  CITY_BURGH_DE_ROTT,
  CITY_BURTHORPE,
  CITY_CAM_TORUM,
  CITY_CANIFIS,
  CITY_CATHERBY,
  CITY_CIVITAS_ILLA_FORTIS,
  CITY_CORSAIR_COVE,
  CITY_DARKMEYER,
  CITY_DORGESH_KAAN,
  CITY_DRAYNOR,
  CITY_EDGEVILLE,
  CITY_ENTRANA,
  CITY_ETCETERIA,
  CITY_FALADOR,
  CITY_GUTANOTH,
  CITY_GWENITH,
  CITY_HOSIDIUS_HOUSE,
  CITY_JATIZSO,
  CITY_KELDAGRIM,
  CITY_LANDS_END,
  CITY_LASSAR_UNDERCITY,
  CITY_LLETYA,
  CITY_LOVAKENGJ_HOUSE,
  CITY_LUMBRIDGE,
  CITY_LUNAR_ISLE,
  CITY_MARIM,
  CITY_MEIYERDITCH,
  CITY_MENAPHOS,
  CITY_MISCELLANIA,
  CITY_MOR_UL_REK,
  CITY_MORTTON,
  CITY_MOS_LE_HARMLESS,
  CITY_MOUNT_KARUULM,
  CITY_MOUNTAIN_CAMP,
  CITY_MYNYDD,
  CITY_NARDAH,
  CITY_NEITIZNOT,
  CITY_PISCARILIUS_HOUSE,
  CITY_PISCATORIS,
  CITY_POLLNIVNEACH,
  CITY_PORT_KHAZARD,
  CITY_PORT_PHASMATYS,
  CITY_PORT_SARIM,
  CITY_PRIFDDINAS,
  CITY_RELLEKKA,
  CITY_RIMMINGTON,
  CITY_SEERS_VILLAGE,
  CITY_SHAYZIEN_HOUSE,
  CITY_SHILO_VILLAGE,
  CITY_SLEPE,
  CITY_SOPHANEM,
  CITY_TAI_BWO_WANNAI,
  CITY_TAVERLEY,
  CITY_TREE_GNOME_STRONGHOLD,
  CITY_TREE_GNOME_VILLAGE,
  CITY_TROLL_STRONGHOLD,
  CITY_UZER,
  CITY_UZER_OASIS,
  CITY_VARROCK,
  CITY_VER_SINHAZA,
  CITY_VOID_OUTPOST,
  CITY_WEISS,
  CITY_WITCHHAVEN,
  CITY_YANILLE,
  CITY_ZANARIS,
  CITY_ZULANDRA,
  DUNGEON_ABANDONED_MINE,
  DUNGEON_AH_ZA_RHOON,
  DUNGEON_ANCIENT_CAVERN,
  DUNGEON_APE_ATOLL,
  DUNGEON_APE_ATOLL_BANANA_PLANTATION,
  DUNGEON_ARDY_BASEMENT,
  DUNGEON_ARDY_SEWERS,
  DUNGEON_ASGARNIAN_ICE_CAVES,
  DUNGEON_BERVIRIUS_TOMB,
  DUNGEON_BRIMHAVEN,
  DUNGEON_BRINE_RAT_CAVERN,
  DUNGEON_CATACOMBS_OF_KOUREND,
  DUNGEON_CERBERUS_LAIR,
  DUNGEON_CHAMPIONS_CHALLENGE,
  DUNGEON_CHAOS_DRUID_TOWER,
  DUNGEON_CHASM_OF_FIRE,
  DUNGEON_CHASM_OF_TEARS,
  DUNGEON_CHINCHOMPA,
  DUNGEON_CIVITAS_ILLA_FORTIS,
  DUNGEON_CLOCK_TOWER,
  DUNGEON_CORSAIR_COVE,
  DUNGEON_CRABCLAW_CAVES,
  DUNGEON_CRANDOR,
  DUNGEON_CRASH_SITE_CAVERN,
  DUNGEON_CRUMBLING_TOWER,
  DUNGEON_DAEYALT_ESSENCE_MINE,
  DUNGEON_DIGSITE,
  DUNGEON_DORGESHKAAN,
  DUNGEON_DORGESHUUN_MINES,
  DUNGEON_DRAYNOR_SEWERS,
  DUNGEON_DWARVEN_MINES,
  DUNGEON_EAGLES_PEAK,
  DUNGEON_ECTOFUNTUS,
  DUNGEON_EDGEVILLE,
  DUNGEON_ELEMENTAL_WORKSHOP,
  DUNGEON_ELVEN_RABBIT_CAVE,
  DUNGEON_ENAKHRAS_TEMPLE,
  DUNGEON_EVIL_CHICKENS_LAIR,
  DUNGEON_EXPERIMENT_CAVE,
  DUNGEON_FEROX_ENCLAVE,
  DUNGEON_FORTHOS,
  DUNGEON_FREMENNIK_SLAYER,
  DUNGEON_GLARIALS_TOMB,
  DUNGEON_GOBLIN_CAVE,
  DUNGEON_GRAND_TREE_TUNNELS,
  DUNGEON_HAM_HIDEOUT,
  DUNGEON_HAM_STORE_ROOM,
  DUNGEON_HEROES_GUILD,
  DUNGEON_IORWERTH,
  DUNGEON_ISLE_OF_SOULS,
  DUNGEON_JATIZSO_MINES,
  DUNGEON_JIGGIG_BURIAL_TOMB,
  DUNGEON_JOGRE,
  DUNGEON_KARAMJA,
  DUNGEON_KARUULM,
  DUNGEON_KGP_HEADQUARTERS,
  DUNGEON_KRUK,
  DUNGEON_LEGENDS_GUILD,
  DUNGEON_LIGHTHOUSE,
  DUNGEON_LIZARDMAN_CAVES,
  DUNGEON_LIZARDMAN_TEMPLE,
  DUNGEON_LUMBRIDGE_SWAMP_CAVES,
  DUNGEON_LUNAR_ISLE_MINE,
  DUNGEON_MANIACAL_HUNTER,
  DUNGEON_MEIYERDITCH_MINE,
  DUNGEON_MISCELLANIA,
  DUNGEON_MOGRE_CAMP,
  DUNGEON_MOS_LE_HARMLESS_CAVES,
  DUNGEON_MOTHERLODE_MINE,
  DUNGEON_MOURNER_TUNNELS,
  DUNGEON_MOUSE_HOLE,
  DUNGEON_MEIYERDITCH_LABORATORIES,
  DUNGEON_MYREQUE,
  DUNGEON_MYTHS_GUILD,
  DUNGEON_OBSERVATORY,
  DUNGEON_OGRE_ENCLAVE,
  DUNGEON_OURANIA,
  DUNGEON_QUIDAMORTEM_CAVE,
  DUNGEON_RASHILIYIAS_TOMB,
  DUNGEON_RUINS_OF_CAMDOZAAL,
  DUNGEON_SALT_MINE,
  DUNGEON_SARADOMINSHRINE,
  DUNGEON_SHADE_CATACOMBS,
  DUNGEON_SHADOW,
  DUNGEON_SHAYZIEN_CRYPTS,
  DUNGEON_SISTERHOOD_SANCTUARY,
  DUNGEON_SMOKE,
  DUNGEON_SOPHANEM,
  DUNGEON_SOURHOG_CAVE,
  DUNGEON_STRONGHOLD_SECURITY,
  DUNGEON_STRONGHOLD_SLAYER,
  DUNGEON_TARNS_LAIR,
  DUNGEON_TAVERLEY,
  DUNGEON_TEMPLE_OF_IKOV,
  DUNGEON_TEMPLE_OF_LIGHT,
  DUNGEON_TEMPLE_OF_MARIMBO,
  DUNGEON_THE_BURROW,
  DUNGEON_THE_WARRENS,
  DUNGEON_TOLNA,
  DUNGEON_TOWER_OF_LIFE,
  DUNGEON_TRAHAEARN_MINE,
  DUNGEON_TUNNEL_OF_CHAOS,
  DUNGEON_UNDERGROUND_PASS,
  DUNGEON_VARROCKSEWERS,
  DUNGEON_VIYELDI_CAVES,
  DUNGEON_WARRIORS_GUILD,
  DUNGEON_WATER_RAVINE,
  DUNGEON_WATERBIRTH,
  DUNGEON_WATERFALL,
  DUNGEON_WEREWOLF_AGILITY,
  DUNGEON_WHITE_WOLF_MOUNTAIN_CAVES,
  DUNGEON_WITCHAVEN_SHRINE,
  DUNGEON_WIZARDS_TOWER,
  DUNGEON_WOODCUTTING_GUILD,
  DUNGEON_WYVERN_CAVE,
  DUNGEON_YANILLE_AGILITY,
  MG_ARDOUGNE_RAT_PITS,
  MG_BARBARIAN_ASSAULT,
  MG_BARROWS,
  MG_BLAST_FURNACE,
  MG_BRIMHAVEN_AGILITY_ARENA,
  MG_BURTHORPE_GAMES_ROOM,
  MG_CASTLE_WARS,
  MG_CLAN_WARS,
  MG_PVP_ARENA,
  MG_FISHING_TRAWLER,
  MG_FORTIS_COLOSSEUM,
  MG_FORTIS_COLOSSEUM_LOBBY,
  MG_GAUNTLET,
  MG_CORRUPTED_GAUNTLET,
  MG_GIANTS_FOUNDRY,
  MG_GUARDIANS_OF_THE_RIFT,
  MG_HALLOWED_SEPULCHRE,
  MG_INFERNO,
  MG_KELDAGRIM_RAT_PITS,
  MG_LAST_MAN_STANDING_DESERTED_ISLAND,
  MG_LAST_MAN_STANDING_WILD_VARROCK,
  MG_MAGE_TRAINING_ARENA,
  MG_NIGHTMARE_ZONE,
  MG_PEST_CONTROL,
  MG_PORT_SARIM_RAT_PITS,
  MG_PYRAMID_PLUNDER,
  MG_ROGUES_DEN,
  MG_SORCERESS_GARDEN,
  MG_SOUL_WARS,
  MG_TEMPLE_TREKKING,
  MG_TITHE_FARM,
  MG_TROUBLE_BREWING,
  MG_TZHAAR_FIGHT_CAVES,
  MG_TZHAAR_FIGHT_PITS,
  MG_VARROCK_RAT_PITS,
  MG_VOLCANIC_MINE,
  RAIDS_CHAMBERS_OF_XERIC,
  RAIDS_THEATRE_OF_BLOOD,
  RAIDS_TOMBS_OF_AMASCUT,
  RAIDS_JALTEVAS_PYRAMID,
  RAIDS_OSMUMTENS_BURIAL_CHAMBER,
  REGION_ABYSSAL_AREA,
  REGION_ABYSSAL_NEXUS,
  REGION_AGILITY_PYRAMID,
  REGION_AIR_ALTAR,
  REGION_AL_KHARID_MINE,
  REGION_ANCIENT_VAULT,
  REGION_APE_ATOLL,
  REGION_ARANDAR,
  REGION_ASGARNIA,
  REGION_AVIUM_SAVANNAH,
  REGION_BATTLEFIELD,
  REGION_BATTLEFRONT,
  REGION_BLAST_MINE,
  REGION_BODY_ALTAR,
  REGION_CHAOS_ALTAR,
  REGION_COSMIC_ALTAR,
  REGION_COSMIC_ENTITYS_PLANE,
  REGION_CRABCLAW_ISLE,
  REGION_CRAFTING_GUILD,
  REGION_CRANDOR,
  REGION_CRASH_ISLAND,
  REGION_DARK_ALTAR,
  REGION_DEATH_ALTAR,
  REGION_DEATH_PLATEAU,
  REGION_DENSE_ESSENCE,
  REGION_DESERT_PLATEAU,
  REGION_DIGSITE,
  REGION_DRAGONTOOTH,
  REGION_DRAYNOR_MANOR,
  REGION_DRILL_SERGEANT,
  REGION_EAGLES_PEAK,
  REGION_EARTH_ALTAR,
  REGION_ENCHANTED_VALLEY,
  REGION_EVIL_TWIN,
  REGION_EXAM_CENTRE,
  REGION_FALADOR_FARM,
  REGION_FARMING_GUILD,
  REGION_FELDIP_HILLS,
  REGION_FENKENSTRAIN,
  REGION_FIGHT_ARENA,
  REGION_FIRE_ALTAR,
  REGION_FISHER_REALM,
  REGION_FISHING_GUILD,
  REGION_FISHING_PLATFORM,
  REGION_FORSAKEN_TOWER,
  REGION_FOSSIL_ISLAND,
  REGION_FREAKY_FORESTER,
  REGION_FREMENNIK,
  REGION_FREMENNIK_ISLES,
  REGION_FROGLAND,
  REGION_GALVEK_SHIPWRECKS,
  REGION_GHORROCK_DUNGEON,
  REGION_GORAKS_PLANE,
  REGION_GRAND_EXCHANGE,
  REGION_GWD,
  REGION_HARMONY,
  REGION_HAZELMERE,
  REGION_HUNTER_GUILD,
  REGION_ICE_PATH,
  REGION_ICEBERG,
  REGION_ICYENE_GRAVEYARD,
  REGION_ISAFDAR,
  REGION_ISLAND_OF_STONE,
  REGION_ISLE_OF_SOULS,
  REGION_JIGGIG,
  REGION_KANDARIN,
  REGION_KARAMJA,
  REGION_KEBOS_LOWLANDS,
  REGION_KEBOS_SWAMP,
  REGION_KHARAZI_JUNGLE,
  REGION_KHARIDIAN_DESERT,
  REGION_KILLERWATT_PLANE,
  REGION_KOUREND,
  REGION_KOUREND_WOODLAND,
  REGION_LAW_ALTAR,
  REGION_LEGENDS_GUILD,
  REGION_LIGHTHOUSE,
  REGION_LITHKREN,
  REGION_LUMBRIDGE_SWAMP,
  REGION_MAX_ISLAND,
  REGION_MCGRUBORS_WOOD,
  REGION_MIME_STAGE,
  REGION_MIND_ALTAR,
  REGION_MISTHALIN,
  REGION_MOLCH,
  REGION_MOLCH_ISLAND,
  REGION_MORYTANIA,
  REGION_MOUNT_QUIDAMORTEM,
  REGION_MR_MORDAUTS_CLASSROOM,
  REGION_MUDSKIPPER,
  REGION_MYSTERIOUS_OLD_MAN_MAZE,
  REGION_MYTHS_GUILD,
  REGION_NATURE_ALTAR,
  REGION_NECROPOLIS,
  REGION_NORTHERN_TUNDRAS,
  REGION_OBSERVATORY,
  REGION_ODD_ONE_OUT,
  REGION_ORTUS_FARM,
  REGION_OTTOS_GROTTO,
  REGION_OURANIA_HUNTER,
  REGION_PIRATES_COVE,
  REGION_PISCATORIS_HUNTER_AREA,
  REGION_POH,
  REGION_POISON_WASTE,
  REGION_PORT_TYRAS,
  REGION_PURO_PURO,
  REGION_QUARRY,
  REGION_RALOS_RISE,
  REGION_RANGING_GUILD,
  REGION_RATCATCHERS_MANSION,
  REGION_RUINS_OF_UNKAH,
  REGION_RUINS_OF_ULLEK,
  REGION_RUNE_ESSENCE_MINE,
  REGION_SCAPERUNE,
  REGION_SEA_SPIRIT_DOCK,
  REGION_SHIP_YARD,
  REGION_SILVAREA,
  REGION_SINCLAR_MANSION,
  REGION_SLAYER_TOWER,
  REGION_SOUL_ALTAR,
  REGION_STRANGLEWOOD_TEMPLE,
  REGION_SUNSET_COAST,
  REGION_THE_SCAR,
  REGION_THE_STRANGLEWOOD,
  REGION_TROLL_ARENA,
  REGION_TROLLHEIM,
  REGION_TROLLWEISS_MTN,
  REGION_TUTORIAL_ISLAND,
  REGION_UNDERWATER,
  REGION_WATER_ALTAR,
  REGION_WATERBIRTH_ISLAND,
  REGION_WINTERTODT_CAMP,
  REGION_WIZARDS_TOWER,
  REGION_WOODCUTTING_GUILD,
  REGION_WRATH_ALTAR,
  WILDERNESS_1_8,
  WILDERNESS_9_16,
  WILDERNESS_17_24,
  WILDERNESS_25_32,
  WILDERNESS_33_40,
  WILDERNESS_41_48,
  WILDERNESS_49_56;

  private static final JsonEnumData<Region, Data> DATA =
      new JsonEnumData<>(values(), Data.class, "RegionData");

  // Built by load(); null until then.
  private static volatile Map<Integer, Region> fromRegion;

  /** One entry of the json. */
  @Getter
  @AllArgsConstructor
  public static class Data {
    private final String name;
    private final int[] ids;
  }

  /** Loads the data and builds the region id lookup. Safe to call more than once. */
  public static synchronized void load(Gson gson) {
    DATA.load(gson);

    if (fromRegion != null) {
      return;
    }

    ImmutableMap.Builder<Integer, Region> regionMapBuilder = new ImmutableMap.Builder<>();
    for (Region region : Region.values()) {
      for (int regionId : region.getIds()) {
        regionMapBuilder.put(regionId, region);
      }
    }

    fromRegion = regionMapBuilder.build();
  }

  public static Region get(final int regionId) {
    Map<Integer, Region> lookup = fromRegion;
    if (lookup == null) {
      throw new IllegalStateException("Region isn't loaded; call Region.load(Gson) first");
    }

    return lookup.get(regionId);
  }

  public Data getData() {
    return DATA.get(this);
  }

  public String getName() {
    return getData().getName();
  }

  public int[] getIds() {
    return getData().getIds();
  }
}