/*
 * Copyright (c) 2022, Thource <https://github.com/Thource>
 * Copyright (c) 2018, Lotto <https://github.com/devLotto>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package dev.thource.runelite.dudewheresmystuff.stash;

import javax.annotation.Nonnull;
import lombok.Getter;
import net.runelite.api.ItemID;
import net.runelite.client.plugins.cluescrolls.clues.emote.STASHUnit;
import net.runelite.client.plugins.cluescrolls.clues.item.ItemRequirement;
import net.runelite.client.plugins.cluescrolls.clues.item.ItemRequirements;

/** StashUnit is used to define which items live at which locations. */
// Suppress duplicate string literal warning because this class is copied from runelite
@SuppressWarnings("java:S1192")
@Getter
public enum StashUnit {
  NORTHEAST_CORNER_OF_THE_KHARAZI_JUNGLE(
      "Kharazi Jungle",
      "North-east corner of the Kharazi Jungle",
      STASHUnit.NORTHEAST_CORNER_OF_THE_KHARAZI_JUNGLE,
      new int[]{ItemID.GUTHIX_STOLE, ItemID.RUNE_SHIELD_H1},
      ItemRequirements.any(
          "Any stole",
          ItemRequirements.item(ItemID.GUTHIX_STOLE),
          ItemRequirements.item(ItemID.SARADOMIN_STOLE),
          ItemRequirements.item(ItemID.ZAMORAK_STOLE),
          ItemRequirements.item(ItemID.ARMADYL_STOLE),
          ItemRequirements.item(ItemID.BANDOS_STOLE),
          ItemRequirements.item(ItemID.ANCIENT_STOLE)),
      ItemRequirements.any(
          "Any heraldic rune shield",
          ItemRequirements.item(ItemID.RUNE_SHIELD_H1),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H2),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H3),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H4),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H5))),
  BARBARIAN_OUTPOST_OBSTACLE_COURSE(
      "Barbarian Outpost",
      "Barbarian Outpost obstacle course",
      STASHUnit.BARBARIAN_OUTPOST_OBSTACLE_COURSE,
      new int[]{ItemID.STEEL_PLATEBODY, ItemID.MAPLE_SHORTBOW, ItemID.TEAM1_CAPE},
      ItemRequirements.item(ItemID.STEEL_PLATEBODY),
      ItemRequirements.item(ItemID.MAPLE_SHORTBOW),
      ItemRequirements.range(ItemID.TEAM1_CAPE, ItemID.TEAM50_CAPE)),
  SOUTHEAST_CORNER_OF_THE_MONASTERY(
      "Edgeville Monastery",
      "South-east corner of the Monastery",
      STASHUnit.SOUTHEAST_CORNER_OF_THE_MONASTERY,
      new int[]{ItemID.HOLY_BOOK},
      ItemRequirements.any(
          "Any god book",
          ItemRequirements.item(ItemID.HOLY_BOOK),
          ItemRequirements.item(ItemID.BOOK_OF_BALANCE),
          ItemRequirements.item(ItemID.UNHOLY_BOOK),
          ItemRequirements.item(ItemID.BOOK_OF_LAW),
          ItemRequirements.item(ItemID.BOOK_OF_WAR),
          ItemRequirements.item(ItemID.BOOK_OF_DARKNESS),
          ItemRequirements.item(ItemID.HOLY_BOOK_OR),
          ItemRequirements.item(ItemID.BOOK_OF_BALANCE_OR),
          ItemRequirements.item(ItemID.UNHOLY_BOOK_OR),
          ItemRequirements.item(ItemID.BOOK_OF_LAW_OR),
          ItemRequirements.item(ItemID.BOOK_OF_WAR_OR),
          ItemRequirements.item(ItemID.BOOK_OF_DARKNESS_OR))),
  ENTRANCE_OF_THE_CAVE_OF_DAMIS(
      "Shadow dungeon",
      "Entrance of the cave of Damis",
      STASHUnit.ENTRANCE_OF_THE_CAVE_OF_DAMIS,
      new int[]{
          ItemID.GUTHIX_MITRE, ItemID.RUNE_CROSSBOW, ItemID.CLIMBING_BOOTS,
          ItemID.RING_OF_VISIBILITY
      },
      ItemRequirements.any(
          "Any mitre",
          ItemRequirements.item(ItemID.GUTHIX_MITRE),
          ItemRequirements.item(ItemID.SARADOMIN_MITRE),
          ItemRequirements.item(ItemID.ZAMORAK_MITRE),
          ItemRequirements.item(ItemID.ANCIENT_MITRE),
          ItemRequirements.item(ItemID.BANDOS_MITRE),
          ItemRequirements.item(ItemID.ARMADYL_MITRE)),
      ItemRequirements.any(
          "Rune crossbow",
          ItemRequirements.item(ItemID.RUNE_CROSSBOW),
          ItemRequirements.item(ItemID.RUNE_CROSSBOW_OR)),
      ItemRequirements.any(
          "Climbing boots",
          ItemRequirements.item(ItemID.CLIMBING_BOOTS),
          ItemRequirements.item(ItemID.CLIMBING_BOOTS_G)),
      ItemRequirements.item(ItemID.RING_OF_VISIBILITY)),
  AGILITY_PYRAMID(
      "Agility Pyramid",
      "Agility Pyramid",
      STASHUnit.AGILITY_PYRAMID,
      new int[]{ItemID.MYSTIC_ROBE_TOP, ItemID.RUNE_SHIELD_H1},
      ItemRequirements.item(ItemID.MYSTIC_ROBE_TOP),
      ItemRequirements.any(
          "Any rune heraldic shield",
          ItemRequirements.item(ItemID.RUNE_SHIELD_H1),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H2),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H3),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H4),
          ItemRequirements.item(ItemID.RUNE_SHIELD_H5))),
  WELL_OF_VOYAGE(
      "Iban's temple",
      "Well of Voyage",
      STASHUnit.WELL_OF_VOYAGE,
      new int[]{ItemID.IBANS_STAFF, ItemID.MYSTIC_ROBE_TOP_DARK, ItemID.MYSTIC_ROBE_BOTTOM_DARK},
      ItemRequirements.any(
          "Any iban's staff",
          ItemRequirements.item(ItemID.IBANS_STAFF),
          ItemRequirements.item(ItemID.IBANS_STAFF_U)),
      ItemRequirements.item(ItemID.MYSTIC_ROBE_TOP_DARK),
      ItemRequirements.item(ItemID.MYSTIC_ROBE_BOTTOM_DARK)),
  SOUTHEAST_CORNER_OF_THE_FISHING_PLATFORM(
      "Fishing Platform",
      "South-east corner of the Fishing Platform",
      STASHUnit.SOUTHEAST_CORNER_OF_THE_FISHING_PLATFORM,
      new int[]{ItemID.AMULET_OF_GLORY, ItemID.BARROWS_GLOVES, ItemID.DRAGON_MED_HELM},
      ItemRequirements.any(
          "Any amulet of glory",
          ItemRequirements.item(ItemID.AMULET_OF_GLORY),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY1),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY2),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY3),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY4),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY5),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY6)),
      ItemRequirements.item(ItemID.BARROWS_GLOVES),
      ItemRequirements.item(ItemID.DRAGON_MED_HELM)),
  DEATH_ALTAR(
      "Death altar",
      "Death Altar",
      STASHUnit.DEATH_ALTAR,
      new int[]{ItemID.RING_OF_WEALTH, ItemID.DEATH_TIARA, ItemID.CAPE_OF_LEGENDS},
      ItemRequirements.any(
          "Any ring of wealth",
          ItemRequirements.item(ItemID.RING_OF_WEALTH),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_1),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_2),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_3),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_4),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_5),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_I),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_I1),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_I2),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_I3),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_I4),
          ItemRequirements.item(ItemID.RING_OF_WEALTH_I5)),
      ItemRequirements.item(ItemID.DEATH_TIARA),
      ItemRequirements.item(ItemID.CAPE_OF_LEGENDS)),
  OUTSIDE_THE_BAR_BY_THE_FIGHT_ARENA(
      "Fight Arena pub",
      "Outside the bar by the Fight Arena",
      STASHUnit.OUTSIDE_THE_BAR_BY_THE_FIGHT_ARENA,
      new int[]{ItemID.PIRATE_BANDANA, ItemID.DRAGON_NECKLACE, ItemID.MAGIC_LONGBOW},
      ItemRequirements.any(
          "Any pirate bandana",
          ItemRequirements.item(ItemID.PIRATE_BANDANA),
          ItemRequirements.item(ItemID.PIRATE_BANDANA_7124),
          ItemRequirements.item(ItemID.PIRATE_BANDANA_7130),
          ItemRequirements.item(ItemID.PIRATE_BANDANA_7136)),
      ItemRequirements.item(ItemID.DRAGON_NECKLACE),
      ItemRequirements.item(ItemID.MAGIC_LONGBOW)),
  BARROWS_CHEST(
      "Barrows chest",
      "Barrows Chest",
      STASHUnit.BARROWS_CHEST,
      new int[]{
          ItemID.DHAROKS_HELM,
          ItemID.DHAROKS_GREATAXE,
          ItemID.DHAROKS_PLATEBODY,
          ItemID.DHAROKS_PLATELEGS
      },
      ItemRequirements.any(
          "Any full barrows set",
          ItemRequirements.all(
              ItemRequirements.any(
                  "Ahrim's hood",
                  ItemRequirements.item(ItemID.AHRIMS_HOOD),
                  ItemRequirements.range(ItemID.AHRIMS_HOOD_100, ItemID.AHRIMS_HOOD_0)),
              ItemRequirements.any(
                  "Ahrim's staff",
                  ItemRequirements.item(ItemID.AHRIMS_STAFF),
                  ItemRequirements.range(ItemID.AHRIMS_STAFF_100, ItemID.AHRIMS_STAFF_0)),
              ItemRequirements.any(
                  "Ahrim's robetop",
                  ItemRequirements.item(ItemID.AHRIMS_ROBETOP),
                  ItemRequirements.range(ItemID.AHRIMS_ROBETOP_100, ItemID.AHRIMS_ROBETOP_0)),
              ItemRequirements.any(
                  "Ahrim's robeskirt",
                  ItemRequirements.item(ItemID.AHRIMS_ROBESKIRT),
                  ItemRequirements.range(ItemID.AHRIMS_ROBESKIRT_100, ItemID.AHRIMS_ROBESKIRT_0))),
          ItemRequirements.all(
              ItemRequirements.any(
                  "Dharok's helm",
                  ItemRequirements.item(ItemID.DHAROKS_HELM),
                  ItemRequirements.range(ItemID.DHAROKS_HELM_100, ItemID.DHAROKS_HELM_0)),
              ItemRequirements.any(
                  "Dharok's greataxe",
                  ItemRequirements.item(ItemID.DHAROKS_GREATAXE),
                  ItemRequirements.range(ItemID.DHAROKS_GREATAXE_100, ItemID.DHAROKS_GREATAXE_0)),
              ItemRequirements.any(
                  "Dharok's platebody",
                  ItemRequirements.item(ItemID.DHAROKS_PLATEBODY),
                  ItemRequirements.range(ItemID.DHAROKS_PLATEBODY_100, ItemID.DHAROKS_PLATEBODY_0)),
              ItemRequirements.any(
                  "Dharok's platelegs",
                  ItemRequirements.item(ItemID.DHAROKS_PLATELEGS),
                  ItemRequirements.range(
                      ItemID.DHAROKS_PLATELEGS_100, ItemID.DHAROKS_PLATELEGS_0))),
          ItemRequirements.all(
              ItemRequirements.any(
                  "Guthan's helm",
                  ItemRequirements.item(ItemID.GUTHANS_HELM),
                  ItemRequirements.range(ItemID.GUTHANS_HELM_100, ItemID.GUTHANS_HELM_0)),
              ItemRequirements.any(
                  "Guthan's warspear",
                  ItemRequirements.item(ItemID.GUTHANS_WARSPEAR),
                  ItemRequirements.range(ItemID.GUTHANS_WARSPEAR_100, ItemID.GUTHANS_WARSPEAR_0)),
              ItemRequirements.any(
                  "Guthan's platebody",
                  ItemRequirements.item(ItemID.GUTHANS_PLATEBODY),
                  ItemRequirements.range(ItemID.GUTHANS_PLATEBODY_100, ItemID.GUTHANS_PLATEBODY_0)),
              ItemRequirements.any(
                  "Guthan's chainskirt",
                  ItemRequirements.item(ItemID.GUTHANS_CHAINSKIRT),
                  ItemRequirements.range(
                      ItemID.GUTHANS_CHAINSKIRT_100, ItemID.GUTHANS_CHAINSKIRT_0))),
          ItemRequirements.all(
              ItemRequirements.any(
                  "Karil's coif",
                  ItemRequirements.item(ItemID.KARILS_COIF),
                  ItemRequirements.range(ItemID.KARILS_COIF_100, ItemID.KARILS_COIF_0)),
              ItemRequirements.any(
                  "Karil's crossbow",
                  ItemRequirements.item(ItemID.KARILS_CROSSBOW),
                  ItemRequirements.range(ItemID.KARILS_CROSSBOW_100, ItemID.KARILS_CROSSBOW_0)),
              ItemRequirements.any(
                  "Karil's leathertop",
                  ItemRequirements.item(ItemID.KARILS_LEATHERTOP),
                  ItemRequirements.range(ItemID.KARILS_LEATHERTOP_100, ItemID.KARILS_LEATHERTOP_0)),
              ItemRequirements.any(
                  "Karil's leatherskirt",
                  ItemRequirements.item(ItemID.KARILS_LEATHERSKIRT),
                  ItemRequirements.range(
                      ItemID.KARILS_LEATHERSKIRT_100, ItemID.KARILS_LEATHERSKIRT_0))),
          ItemRequirements.all(
              ItemRequirements.any(
                  "Torag's helm",
                  ItemRequirements.item(ItemID.TORAGS_HELM),
                  ItemRequirements.range(ItemID.TORAGS_HELM_100, ItemID.TORAGS_HELM_0)),
              ItemRequirements.any(
                  "Torag's hammers",
                  ItemRequirements.item(ItemID.TORAGS_HAMMERS),
                  ItemRequirements.range(ItemID.TORAGS_HAMMERS_100, ItemID.TORAGS_HAMMERS_0)),
              ItemRequirements.any(
                  "Torag's platebody",
                  ItemRequirements.item(ItemID.TORAGS_PLATEBODY),
                  ItemRequirements.range(ItemID.TORAGS_PLATEBODY_100, ItemID.TORAGS_PLATEBODY_0)),
              ItemRequirements.any(
                  "Torag's platelegs",
                  ItemRequirements.item(ItemID.TORAGS_PLATELEGS),
                  ItemRequirements.range(ItemID.TORAGS_PLATELEGS_100, ItemID.TORAGS_PLATELEGS_0))),
          ItemRequirements.all(
              ItemRequirements.any(
                  "Verac's helm",
                  ItemRequirements.item(ItemID.VERACS_HELM),
                  ItemRequirements.range(ItemID.VERACS_HELM_100, ItemID.VERACS_HELM_0)),
              ItemRequirements.any(
                  "Verac's flail",
                  ItemRequirements.item(ItemID.VERACS_FLAIL),
                  ItemRequirements.range(ItemID.VERACS_FLAIL_100, ItemID.VERACS_FLAIL_0)),
              ItemRequirements.any(
                  "Verac's brassard",
                  ItemRequirements.item(ItemID.VERACS_BRASSARD),
                  ItemRequirements.range(ItemID.VERACS_BRASSARD_100, ItemID.VERACS_BRASSARD_0)),
              ItemRequirements.any(
                  "Verac's plateskirt",
                  ItemRequirements.item(ItemID.VERACS_PLATESKIRT),
                  ItemRequirements.range(
                      ItemID.VERACS_PLATESKIRT_100, ItemID.VERACS_PLATESKIRT_0))))),
  IN_THE_MIDDLE_OF_JIGGIG(
      "Jiggig",
      "In the middle of Jiggig",
      STASHUnit.IN_THE_MIDDLE_OF_JIGGIG,
      new int[]{ItemID.RUNE_HELM_H1, ItemID.RUNE_SPEAR, ItemID.RUNE_PLATELEGS},
      ItemRequirements.range(ItemID.RUNE_HELM_H1, ItemID.RUNE_HELM_H5),
      ItemRequirements.item(ItemID.RUNE_SPEAR),
      ItemRequirements.item(ItemID.RUNE_PLATELEGS)),
  BY_THE_BEAR_CAGE_IN_VARROCK_PALACE_GARDENS(
      "Varrock Castle",
      "By the bear cage in Varrock Palace gardens",
      STASHUnit.BY_THE_BEAR_CAGE_IN_VARROCK_PALACE_GARDENS,
      new int[]{ItemID.ZAMORAK_GODSWORD},
      ItemRequirements.any(
          "Zamorak godsword",
          ItemRequirements.item(ItemID.ZAMORAK_GODSWORD),
          ItemRequirements.item(ItemID.ZAMORAK_GODSWORD_OR))),
  BEHIND_MISS_SCHISM_IN_DRAYNOR_VILLAGE(
      "Draynor Village",
      "Behind Miss Schism in Draynor Village",
      STASHUnit.BEHIND_MISS_SCHISM_IN_DRAYNOR_VILLAGE,
      new int[]{ItemID.ABYSSAL_WHIP, ItemID.CAPE_OF_LEGENDS, ItemID.SPINED_CHAPS},
      ItemRequirements.any(
          "Abyssal whip",
          ItemRequirements.item(ItemID.ABYSSAL_WHIP),
          ItemRequirements.item(ItemID.VOLCANIC_ABYSSAL_WHIP),
          ItemRequirements.item(ItemID.FROZEN_ABYSSAL_WHIP),
          ItemRequirements.item(ItemID.ABYSSAL_WHIP_OR),
          ItemRequirements.item(ItemID.ABYSSAL_TENTACLE),
          ItemRequirements.item(ItemID.ABYSSAL_TENTACLE_OR)),
      ItemRequirements.item(ItemID.CAPE_OF_LEGENDS),
      ItemRequirements.item(ItemID.SPINED_CHAPS)),
  CRYSTALLINE_MAPLE_TREES(
      "North of Prifddinas",
      "North of Prifddinas by several maple trees",
      STASHUnit.CRYSTALLINE_MAPLE_TREES,
      new int[]{ItemID.BRYOPHYTAS_STAFF_UNCHARGED, ItemID.NATURE_TIARA},
      ItemRequirements.range(ItemID.BRYOPHYTAS_STAFF_UNCHARGED, ItemID.BRYOPHYTAS_STAFF),
      ItemRequirements.item(ItemID.NATURE_TIARA)),
  DIGSITE(
      "Digsite",
      "Digsite",
      STASHUnit.DIGSITE,
      new int[]{ItemID.GREEN_HAT, ItemID.SNAKESKIN_BOOTS, ItemID.IRON_PICKAXE},
      ItemRequirements.item(ItemID.GREEN_HAT),
      ItemRequirements.item(ItemID.SNAKESKIN_BOOTS),
      ItemRequirements.item(ItemID.IRON_PICKAXE)),
  SOUTH_OF_THE_SHRINE_IN_TAI_BWO_WANNAI_VILLAGE(
      "Tai Bwo Wannai",
      "South of the shrine in Tai Bwo Wannai Village",
      STASHUnit.SOUTH_OF_THE_SHRINE_IN_TAI_BWO_WANNAI_VILLAGE,
      new int[]{ItemID.GREEN_DHIDE_CHAPS, ItemID.RING_OF_DUELING1, ItemID.MITHRIL_MED_HELM},
      ItemRequirements.item(ItemID.GREEN_DHIDE_CHAPS),
      ItemRequirements.any(
          "Ring of dueling",
          ItemRequirements.item(ItemID.RING_OF_DUELING1),
          ItemRequirements.item(ItemID.RING_OF_DUELING2),
          ItemRequirements.item(ItemID.RING_OF_DUELING3),
          ItemRequirements.item(ItemID.RING_OF_DUELING4),
          ItemRequirements.item(ItemID.RING_OF_DUELING5),
          ItemRequirements.item(ItemID.RING_OF_DUELING6),
          ItemRequirements.item(ItemID.RING_OF_DUELING7),
          ItemRequirements.item(ItemID.RING_OF_DUELING8)),
      ItemRequirements.item(ItemID.MITHRIL_MED_HELM)),
  WEST_OF_THE_SHAYZIEN_COMBAT_RING(
      "Shayzien Combat Ring",
      "North of the Shayzien combat ring",
      STASHUnit.WEST_OF_THE_SHAYZIEN_COMBAT_RING,
      new int[]{ItemID.ADAMANT_PLATELEGS, ItemID.ADAMANT_PLATEBODY, ItemID.ADAMANT_FULL_HELM},
      ItemRequirements.item(ItemID.ADAMANT_PLATELEGS),
      ItemRequirements.item(ItemID.ADAMANT_PLATEBODY),
      ItemRequirements.item(ItemID.ADAMANT_FULL_HELM)),
  TENT_IN_LORD_IORWERTHS_ENCAMPMENT(
      "Lord Iorwerth's camp",
      "Tent in Lord Iorwerth's encampment",
      STASHUnit.TENT_IN_LORD_IORWERTHS_ENCAMPMENT,
      new int[]{ItemID.CRYSTAL_BOW},
      ItemRequirements.any(
          "Crystal Bow",
          ItemRequirements.item(ItemID.CRYSTAL_BOW),
          ItemRequirements.item(ItemID.CRYSTAL_BOW_24123),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25869),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25884),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25886),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25888),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25890),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25892),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25894),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_C_25896),
          ItemRequirements.item(ItemID.BOW_OF_FAERDHINEN_INACTIVE))),
  OUTSIDE_THE_LEGENDS_GUILD_GATES(
      "Legend's Guild",
      "Outside the Legends' Guild gates",
      STASHUnit.OUTSIDE_THE_LEGENDS_GUILD_GATES,
      new int[]{ItemID.IRON_PLATELEGS, ItemID.OAK_LONGBOW, ItemID.EMERALD_AMULET},
      ItemRequirements.item(ItemID.IRON_PLATELEGS),
      ItemRequirements.item(ItemID.OAK_LONGBOW),
      ItemRequirements.item(ItemID.EMERALD_AMULET)),
  OUTSIDE_THE_LEGENDS_GUILD_DOOR(
      "Legend's Guild",
      "Outside the Legends' Guild door",
      STASHUnit.OUTSIDE_THE_LEGENDS_GUILD_DOOR,
      new int[]{ItemID.CAPE_OF_LEGENDS, ItemID.DRAGON_BATTLEAXE, ItemID.AMULET_OF_GLORY},
      ItemRequirements.item(ItemID.CAPE_OF_LEGENDS),
      ItemRequirements.item(ItemID.DRAGON_BATTLEAXE),
      ItemRequirements.any(
          "Any amulet of glory",
          ItemRequirements.item(ItemID.AMULET_OF_GLORY),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY1),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY2),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY3),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY4),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY5),
          ItemRequirements.item(ItemID.AMULET_OF_GLORY6))),
  MUBARIZS_ROOM_AT_THE_DUEL_ARENA(
      "Duel Arena",
      "Mubariz's room at the Duel Arena",
      STASHUnit.PVP_ARENA_TICKET_OFFICE,
      new int[]{ItemID.IRON_CHAINBODY, ItemID.LEATHER_CHAPS, ItemID.COIF},
      ItemRequirements.item(ItemID.IRON_CHAINBODY),
      ItemRequirements.item(ItemID.LEATHER_CHAPS),
      ItemRequirements.item(ItemID.COIF)),
  TOP_FLOOR_OF_THE_LIGHTHOUSE(
      "Lighthouse",
      "Top floor of the Lighthouse",
      STASHUnit.TOP_FLOOR_OF_THE_LIGHTHOUSE,
      new int[]{ItemID.BLUE_DHIDE_BODY, ItemID.BLUE_DHIDE_VAMBRACES},
      ItemRequirements.item(ItemID.BLUE_DHIDE_BODY),
      ItemRequirements.item(ItemID.BLUE_DHIDE_VAMBRACES)),
  SHILO_VILLAGE_BANK(
      "Shilo Village",
      "Shilo Village bank",
      STASHUnit.SHILO_VILLAGE_BANK,
      new int[]{ItemID.MYSTIC_HAT, ItemID.BONE_SPEAR, ItemID.RUNE_PLATEBODY},
      ItemRequirements.item(ItemID.MYSTIC_HAT),
      ItemRequirements.item(ItemID.BONE_SPEAR),
      ItemRequirements.item(ItemID.RUNE_PLATEBODY)),
  NEAR_A_LADDER_IN_THE_WILDERNESS_LAVA_MAZE(
      "Lava maze",
      "Near a ladder in the Wilderness Lava Maze",
      STASHUnit.NEAR_A_LADDER_IN_THE_WILDERNESS_LAVA_MAZE,
      new int[]{ItemID.BLACK_DHIDE_CHAPS, ItemID.SPOTTED_CAPE, ItemID.ROLLING_PIN},
      ItemRequirements.item(ItemID.BLACK_DHIDE_CHAPS),
      ItemRequirements.any(
          "Spotted cape",
          ItemRequirements.item(ItemID.SPOTTED_CAPE),
          ItemRequirements.item(ItemID.SPOTTED_CAPE_10073)),
      ItemRequirements.item(ItemID.ROLLING_PIN)),
  OUTSIDE_KRIL_TSUTSAROTHS_ROOM(
      "K'ril's chamber",
      "Outside K'ril Tsutsaroth's room",
      STASHUnit.OUTSIDE_KRIL_TSUTSAROTHS_ROOM,
      new int[]{ItemID.ZAMORAK_FULL_HELM, ItemID.SHADOW_SWORD},
      ItemRequirements.item(ItemID.ZAMORAK_FULL_HELM),
      ItemRequirements.item(ItemID.SHADOW_SWORD)),
  TAVERLEY_STONE_CIRCLE(
      "Taverley stone circle",
      "Taverley Stone Circle",
      STASHUnit.TAVERLEY_STONE_CIRCLE,
      new int[]{ItemID.BLUE_WIZARD_HAT, ItemID.BRONZE_2H_SWORD, ItemID.HAM_BOOTS},
      ItemRequirements.item(ItemID.BLUE_WIZARD_HAT),
      ItemRequirements.item(ItemID.BRONZE_2H_SWORD),
      ItemRequirements.item(ItemID.HAM_BOOTS)),
  NORTH_OF_EVIL_DAVES_HOUSE_IN_EDGEVILLE(
      "Edgeville",
      "North of Evil Dave's house in Edgeville",
      STASHUnit.NORTH_OF_EVIL_DAVES_HOUSE_IN_EDGEVILLE,
      new int[]{ItemID.BROWN_APRON, ItemID.LEATHER_BOOTS, ItemID.LEATHER_GLOVES},
      ItemRequirements.item(ItemID.BROWN_APRON),
      ItemRequirements.item(ItemID.LEATHER_BOOTS),
      ItemRequirements.item(ItemID.LEATHER_GLOVES)),
  OGRE_CAGE_IN_KING_LATHAS_TRAINING_CAMP(
      "King Lathas' camp",
      "Ogre cage in the Ardougne Training Camp",
      STASHUnit.OGRE_CAGE_IN_KING_LATHAS_TRAINING_CAMP,
      new int[]{ItemID.GREEN_DHIDE_BODY, ItemID.GREEN_DHIDE_CHAPS, ItemID.STEEL_SQ_SHIELD},
      ItemRequirements.item(ItemID.GREEN_DHIDE_BODY),
      ItemRequirements.item(ItemID.GREEN_DHIDE_CHAPS),
      ItemRequirements.item(ItemID.STEEL_SQ_SHIELD)),
  ENTRANA_CHAPEL(
      "Entrana church",
      "Entrana Chapel",
      STASHUnit.ENTRANA_CHAPEL,
      new int[]{ItemID.BLACK_DHIDE_VAMBRACES, ItemID.BLACK_DHIDE_CHAPS, ItemID.BLACK_DHIDE_BODY},
      ItemRequirements.item(ItemID.BLACK_DHIDE_VAMBRACES),
      ItemRequirements.item(ItemID.BLACK_DHIDE_CHAPS),
      ItemRequirements.item(ItemID.BLACK_DHIDE_BODY)),
  NEAR_THE_ENTRANA_FERRY_IN_PORT_SARIM(
      "Port Sarim",
      "Near the Entrana ferry in Port Sarim",
      STASHUnit.NEAR_THE_ENTRANA_FERRY_IN_PORT_SARIM,
      new int[]{ItemID.COIF, ItemID.STEEL_PLATESKIRT, ItemID.SAPPHIRE_NECKLACE},
      ItemRequirements.item(ItemID.COIF),
      ItemRequirements.item(ItemID.STEEL_PLATESKIRT),
      ItemRequirements.item(ItemID.SAPPHIRE_NECKLACE)),
  OUTSIDE_THE_DIGSITE_EXAM_CENTRE(
      "Exam Centre",
      "Outside the Digsite Exam Centre",
      STASHUnit.OUTSIDE_THE_DIGSITE_EXAM_CENTRE,
      new int[]{ItemID.WHITE_APRON, ItemID.GREEN_BOOTS, ItemID.LEATHER_GLOVES},
      ItemRequirements.item(ItemID.WHITE_APRON),
      ItemRequirements.item(ItemID.GREEN_BOOTS),
      ItemRequirements.item(ItemID.LEATHER_GLOVES)),
  ON_THE_BRIDGE_TO_THE_MISTHALIN_WIZARDS_TOWER(
      "Wizards' Tower",
      "On the bridge to the Misthalin Wizards' Tower",
      STASHUnit.ON_THE_BRIDGE_TO_THE_MISTHALIN_WIZARDS_TOWER,
      new int[]{ItemID.IRON_MED_HELM, ItemID.EMERALD_RING, ItemID.WHITE_APRON},
      ItemRequirements.item(ItemID.IRON_MED_HELM),
      ItemRequirements.item(ItemID.EMERALD_RING),
      ItemRequirements.item(ItemID.WHITE_APRON)),
  UPSTAIRS_IN_THE_ARDOUGNE_WINDMILL(
      "East Ardougne",
      "Upstairs in the Ardougne windmill",
      STASHUnit.UPSTAIRS_IN_THE_ARDOUGNE_WINDMILL,
      new int[]{ItemID.BLUE_ROBE_TOP, ItemID.HAM_ROBE, ItemID.TIARA},
      ItemRequirements.item(ItemID.BLUE_ROBE_TOP),
      ItemRequirements.item(ItemID.HAM_ROBE),
      ItemRequirements.item(ItemID.TIARA)),
  OUTSIDE_THE_SEERS_VILLAGE_COURTHOUSE(
      "Seers Village",
      "Outside the Seers' Village courthouse",
      STASHUnit.OUTSIDE_THE_SEERS_VILLAGE_COURTHOUSE,
      new int[]{ItemID.ADAMANT_HALBERD, ItemID.MYSTIC_ROBE_BOTTOM, ItemID.DIAMOND_RING},
      ItemRequirements.item(ItemID.ADAMANT_HALBERD),
      ItemRequirements.item(ItemID.MYSTIC_ROBE_BOTTOM),
      ItemRequirements.item(ItemID.DIAMOND_RING)),
  OUTSIDE_THE_WILDERNESS_AXE_HUT(
      "Magic axe hut",
      "Outside the Wilderness axe hut",
      STASHUnit.OUTSIDE_THE_WILDERNESS_AXE_HUT,
      new int[]{ItemID.FLARED_TROUSERS, ItemID.LOCKPICK},
      ItemRequirements.item(ItemID.FLARED_TROUSERS),
      ItemRequirements.item(ItemID.LOCKPICK)),
  NORTH_OF_MOUNT_KARUULM(
      "Mount Karuulm",
      "North of Mount Karuulm",
      STASHUnit.NORTH_OF_MOUNT_KARUULM,
      new int[]{ItemID.ADAMANT_WARHAMMER, ItemID.RING_OF_LIFE, ItemID.MITHRIL_BOOTS},
      ItemRequirements.item(ItemID.ADAMANT_WARHAMMER),
      ItemRequirements.item(ItemID.RING_OF_LIFE),
      ItemRequirements.item(ItemID.MITHRIL_BOOTS)),
  HICKTONS_ARCHERY_EMPORIUM(
      "Catherby",
      "Hickton's Archery Emporium",
      STASHUnit.HICKTONS_ARCHERY_EMPORIUM,
      new int[]{ItemID.BLUE_BOOTS, ItemID.HARDLEATHER_BODY, ItemID.SILVER_SICKLE},
      ItemRequirements.item(ItemID.BLUE_BOOTS),
      ItemRequirements.item(ItemID.HARDLEATHER_BODY),
      ItemRequirements.item(ItemID.SILVER_SICKLE)),
  OUTSIDE_HARRYS_FISHING_SHOP_IN_CATHERBY(
      "Catherby",
      "Outside Harry's Fishing Shop in Catherby",
      STASHUnit.OUTSIDE_HARRYS_FISHING_SHOP_IN_CATHERBY,
      new int[]{ItemID.ADAMANT_SQ_SHIELD, ItemID.BONE_DAGGER, ItemID.MITHRIL_PLATEBODY},
      ItemRequirements.item(ItemID.ADAMANT_SQ_SHIELD),
      ItemRequirements.item(ItemID.BONE_DAGGER),
      ItemRequirements.item(ItemID.MITHRIL_PLATEBODY)),
  GNOME_STRONGHOLD_BALANCING_ROPE(
      "Gnome Stronghold",
      "Gnome Stronghold balancing rope",
      STASHUnit.GNOME_STRONGHOLD_BALANCING_ROPE,
      new int[]{ItemID.STEEL_KITESHIELD, ItemID.RING_OF_FORGING, ItemID.GREEN_DHIDE_CHAPS},
      ItemRequirements.item(ItemID.STEEL_KITESHIELD),
      ItemRequirements.item(ItemID.RING_OF_FORGING),
      ItemRequirements.item(ItemID.GREEN_DHIDE_CHAPS)),
  TZHAAR_GEM_STORE(
      "Tzhaar gem store",
      "TzHaar gem store",
      STASHUnit.TZHAAR_GEM_STORE,
      new int[]{ItemID.FIRE_CAPE, ItemID.TOKTZXILUL},
      ItemRequirements.any(
          "Fire cape",
          ItemRequirements.item(ItemID.FIRE_CAPE),
          ItemRequirements.item(ItemID.FIRE_CAPE_L),
          ItemRequirements.item(ItemID.FIRE_MAX_CAPE),
          ItemRequirements.item(ItemID.FIRE_MAX_CAPE_L),
          ItemRequirements.item(ItemID.INFERNAL_CAPE),
          ItemRequirements.item(ItemID.INFERNAL_CAPE_L),
          ItemRequirements.item(ItemID.INFERNAL_MAX_CAPE_21285),
          ItemRequirements.item(ItemID.INFERNAL_MAX_CAPE_L)),
      ItemRequirements.item(ItemID.TOKTZXILUL)),
  OUTSIDE_DRAYNOR_VILLAGE_JAIL(
      "Draynor Village jail",
      "Outside Draynor Village jail",
      STASHUnit.OUTSIDE_DRAYNOR_VILLAGE_JAIL,
      new int[]{ItemID.ADAMANT_SWORD, ItemID.SAPPHIRE_AMULET, ItemID.ADAMANT_PLATESKIRT},
      ItemRequirements.item(ItemID.ADAMANT_SWORD),
      ItemRequirements.item(ItemID.SAPPHIRE_AMULET),
      ItemRequirements.item(ItemID.ADAMANT_PLATESKIRT)),
  CROSSROADS_NORTH_OF_DRAYNOR_VILLAGE(
      "Draynor Village",
      "Crossroads north of Draynor Village",
      STASHUnit.CROSSROADS_NORTH_OF_DRAYNOR_VILLAGE,
      new int[]{ItemID.IRON_CHAINBODY, ItemID.SAPPHIRE_RING, ItemID.LONGBOW},
      ItemRequirements.item(ItemID.IRON_CHAINBODY),
      ItemRequirements.item(ItemID.SAPPHIRE_RING),
      ItemRequirements.item(ItemID.LONGBOW)),
  OUTSIDE_THE_FALADOR_PARTY_ROOM(
      "Falador Party Room",
      "Outside the Falador Party Room",
      STASHUnit.OUTSIDE_THE_FALADOR_PARTY_ROOM,
      new int[]{ItemID.STEEL_FULL_HELM, ItemID.STEEL_PLATEBODY, ItemID.IRON_PLATESKIRT},
      ItemRequirements.item(ItemID.STEEL_FULL_HELM),
      ItemRequirements.item(ItemID.STEEL_PLATEBODY),
      ItemRequirements.item(ItemID.IRON_PLATESKIRT)),
  NEAR_A_SHED_IN_LUMBRIDGE_SWAMP(
      "Lumbridge swamp",
      "Near a shed in Lumbridge Swamp",
      STASHUnit.NEAR_A_SHED_IN_LUMBRIDGE_SWAMP,
      new int[]{ItemID.BRONZE_DAGGER, ItemID.IRON_FULL_HELM, ItemID.GOLD_RING},
      ItemRequirements.item(ItemID.BRONZE_DAGGER),
      ItemRequirements.item(ItemID.IRON_FULL_HELM),
      ItemRequirements.item(ItemID.GOLD_RING)),
  LUMBRIDGE_SWAMP_CAVES(
      "Lumbridge swamp caves",
      "Lumbridge Swamp caves",
      STASHUnit.LUMBRIDGE_SWAMP_CAVES,
      new int[]{ItemID.STAFF_OF_AIR, ItemID.BRONZE_FULL_HELM, ItemID.AMULET_OF_POWER},
      ItemRequirements.item(ItemID.STAFF_OF_AIR),
      ItemRequirements.item(ItemID.BRONZE_FULL_HELM),
      ItemRequirements.item(ItemID.AMULET_OF_POWER)),
  OUTSIDE_THE_GREAT_PYRAMID_OF_SOPHANEM(
      "Pyramid Of Sophanem",
      "Outside the great pyramid of Sophanem",
      STASHUnit.OUTSIDE_THE_GREAT_PYRAMID_OF_SOPHANEM,
      new int[]{ItemID.RING_OF_LIFE, ItemID.AMULET_OF_GLORY, ItemID.ADAMANT_2H_SWORD},
      ItemRequirements.item(ItemID.RING_OF_LIFE),
      ItemRequirements.item(ItemID.AMULET_OF_GLORY),
      ItemRequirements.item(ItemID.ADAMANT_2H_SWORD)),
  CENTRE_OF_CANIFIS(
      "Canifis",
      "Centre of Canifis",
      STASHUnit.CENTRE_OF_CANIFIS,
      new int[]{ItemID.GREEN_ROBE_TOP, ItemID.MITHRIL_PLATELEGS, ItemID.IRON_2H_SWORD},
      ItemRequirements.item(ItemID.GREEN_ROBE_TOP),
      ItemRequirements.item(ItemID.MITHRIL_PLATELEGS),
      ItemRequirements.item(ItemID.IRON_2H_SWORD)),
  KING_BLACK_DRAGONS_LAIR(
      "King black dragon's lair",
      "King Black Dragon's lair",
      STASHUnit.KING_BLACK_DRAGONS_LAIR,
      new int[]{ItemID.BLACK_DHIDE_BODY, ItemID.BLACK_DHIDE_VAMBRACES, ItemID.BLACK_DRAGON_MASK},
      ItemRequirements.item(ItemID.BLACK_DHIDE_BODY),
      ItemRequirements.item(ItemID.BLACK_DHIDE_VAMBRACES),
      ItemRequirements.item(ItemID.BLACK_DRAGON_MASK)),
  SOUTH_OF_THE_GRAND_EXCHANGE(
      "Grand Exchange",
      "South of the Grand Exchange",
      STASHUnit.SOUTH_OF_THE_GRAND_EXCHANGE,
      new int[]{ItemID.PINK_SKIRT, ItemID.PINK_ROBE_TOP, ItemID.BODY_TIARA},
      ItemRequirements.item(ItemID.PINK_SKIRT),
      ItemRequirements.item(ItemID.PINK_ROBE_TOP),
      ItemRequirements.item(ItemID.BODY_TIARA)),
  OUTSIDE_MUDKNUCKLES_HUT(
      "Goblin Village",
      "Outside Mudknuckles' hut",
      STASHUnit.OUTSIDE_MUDKNUCKLES_HUT,
      new int[]{ItemID.BANDOS_PLATEBODY, ItemID.BANDOS_CLOAK, ItemID.BANDOS_GODSWORD},
      ItemRequirements.item(ItemID.BANDOS_PLATEBODY),
      ItemRequirements.item(ItemID.BANDOS_CLOAK),
      ItemRequirements.any(
          "Bandos godsword",
          ItemRequirements.item(ItemID.BANDOS_GODSWORD),
          ItemRequirements.item(ItemID.BANDOS_GODSWORD_OR))),
  AL_KHARID_SCORPION_MINE(
      "Al Kharid mine",
      "Al Kharid scorpion mine",
      STASHUnit.AL_KHARID_SCORPION_MINE,
      new int[]{ItemID.DESERT_SHIRT, ItemID.LEATHER_GLOVES, ItemID.LEATHER_BOOTS},
      ItemRequirements.item(ItemID.DESERT_SHIRT),
      ItemRequirements.item(ItemID.LEATHER_GLOVES),
      ItemRequirements.item(ItemID.LEATHER_BOOTS)),
  INSIDE_THE_DIGSITE_EXAM_CENTRE(
      "Exam Centre",
      "Inside the Digsite Exam Centre",
      STASHUnit.INSIDE_THE_DIGSITE_EXAM_CENTRE,
      new int[]{ItemID.MYSTIC_FIRE_STAFF, ItemID.DIAMOND_BRACELET, ItemID.RUNE_BOOTS},
      ItemRequirements.item(ItemID.MYSTIC_FIRE_STAFF),
      ItemRequirements.item(ItemID.DIAMOND_BRACELET),
      ItemRequirements.item(ItemID.RUNE_BOOTS)),
  OUTSIDE_THE_SLAYER_TOWER_GARGOYLE_ROOM(
      "Slayer Tower",
      "Outside the Slayer Tower gargoyle room",
      STASHUnit.OUTSIDE_THE_SLAYER_TOWER_GARGOYLE_ROOM,
      new int[]{ItemID.SEERCULL, ItemID.COMBAT_BRACELET4, ItemID.HELM_OF_NEITIZNOT},
      ItemRequirements.item(ItemID.SEERCULL),
      ItemRequirements.range(ItemID.COMBAT_BRACELET4, ItemID.COMBAT_BRACELET),
      ItemRequirements.item(ItemID.HELM_OF_NEITIZNOT)),
  OUTSIDE_THE_FISHING_GUILD(
      "Fishing Guild",
      "Outside the Fishing Guild",
      STASHUnit.OUTSIDE_THE_FISHING_GUILD,
      new int[]{ItemID.EMERALD_RING, ItemID.SAPPHIRE_AMULET, ItemID.BRONZE_CHAINBODY},
      ItemRequirements.item(ItemID.EMERALD_RING),
      ItemRequirements.item(ItemID.SAPPHIRE_AMULET),
      ItemRequirements.item(ItemID.BRONZE_CHAINBODY)),
  SHANTAY_PASS(
      "Shantay Pass",
      "Shantay Pass",
      STASHUnit.SHANTAY_PASS,
      new int[]{ItemID.BRUISE_BLUE_SNELM_3343, ItemID.STAFF_OF_AIR, ItemID.BRONZE_SQ_SHIELD},
      ItemRequirements.any(
          "Bruise blue snelm (pointed)", ItemRequirements.item(ItemID.BRUISE_BLUE_SNELM_3343)),
      ItemRequirements.item(ItemID.STAFF_OF_AIR),
      ItemRequirements.item(ItemID.BRONZE_SQ_SHIELD)),
  AUBURYS_SHOP_IN_VARROCK(
      "Varrock rune store",
      "Aubury's shop in Varrock",
      STASHUnit.AUBURYS_SHOP_IN_VARROCK,
      new int[]{ItemID.AIR_TIARA, ItemID.STAFF_OF_WATER},
      ItemRequirements.item(ItemID.AIR_TIARA),
      ItemRequirements.item(ItemID.STAFF_OF_WATER)),
  CATHERBY_BEEHIVE_FIELD(
      "Catherby",
      "Catherby beehive field",
      STASHUnit.CATHERBY_BEEHIVE_FIELD,
      new int[]{ItemID.DESERT_SHIRT, ItemID.GREEN_ROBE_BOTTOMS, ItemID.STEEL_AXE},
      ItemRequirements.item(ItemID.DESERT_SHIRT),
      ItemRequirements.item(ItemID.GREEN_ROBE_BOTTOMS),
      ItemRequirements.item(ItemID.STEEL_AXE)),
  OUTSIDE_YANILLE_BANK(
      "Yanille",
      "Outside Yanille bank",
      STASHUnit.OUTSIDE_YANILLE_BANK,
      new int[]{ItemID.BROWN_APRON, ItemID.ADAMANT_MED_HELM, ItemID.SNAKESKIN_CHAPS},
      ItemRequirements.item(ItemID.BROWN_APRON),
      ItemRequirements.item(ItemID.ADAMANT_MED_HELM),
      ItemRequirements.item(ItemID.SNAKESKIN_CHAPS)),
  TZHAAR_WEAPONS_STORE(
      "Tzhaar weapon store",
      "TzHaar weapons store",
      STASHUnit.TZHAAR_WEAPONS_STORE,
      new int[]{ItemID.STEEL_LONGSWORD, ItemID.BLUE_DHIDE_BODY, ItemID.MYSTIC_GLOVES},
      ItemRequirements.item(ItemID.STEEL_LONGSWORD),
      ItemRequirements.item(ItemID.BLUE_DHIDE_BODY),
      ItemRequirements.item(ItemID.MYSTIC_GLOVES)),
  ENTRANCE_OF_THE_CAVERN_UNDER_THE_WHIRLPOOL(
      "Ancient cavern",
      "Entrance of the cavern under the whirlpool",
      STASHUnit.ENTRANCE_OF_THE_CAVERN_UNDER_THE_WHIRLPOOL,
      new int[]{ItemID.GRANITE_SHIELD, ItemID.SPLITBARK_BODY, ItemID.RUNE_HELM_H1},
      ItemRequirements.item(ItemID.GRANITE_SHIELD),
      ItemRequirements.item(ItemID.SPLITBARK_BODY),
      ItemRequirements.range(ItemID.RUNE_HELM_H1, ItemID.RUNE_HELM_H5)),
  NEAR_A_RUNITE_ROCK_IN_THE_FREMENNIK_ISLES(
      "Fremennik Isles",
      "Near a runite rock in the Fremennik Isles",
      STASHUnit.NEAR_A_RUNITE_ROCK_IN_THE_FREMENNIK_ISLES,
      new int[]{ItemID.RUNE_BOOTS, ItemID.PROSELYTE_HAUBERK, ItemID.DRAGONSTONE_RING},
      ItemRequirements.item(ItemID.RUNE_BOOTS),
      ItemRequirements.item(ItemID.PROSELYTE_HAUBERK),
      ItemRequirements.item(ItemID.DRAGONSTONE_RING)),
  NEAR_THE_PIER_IN_ZULANDRA(
      "Zul-Andra",
      "Near the pier in Zul-Andra",
      STASHUnit.NEAR_THE_PIER_IN_ZULANDRA,
      new int[]{ItemID.DRAGON_2H_SWORD, ItemID.BANDOS_BOOTS, ItemID.OBSIDIAN_CAPE},
      ItemRequirements.item(ItemID.DRAGON_2H_SWORD),
      ItemRequirements.any(
          "Bandos boots",
          ItemRequirements.item(ItemID.BANDOS_BOOTS),
          ItemRequirements.item(ItemID.GUARDIAN_BOOTS)),
      ItemRequirements.item(ItemID.OBSIDIAN_CAPE)),
  FOUNTAIN_OF_HEROES(
      "Fountain of heroes",
      "Fountain of Heroes",
      STASHUnit.FOUNTAIN_OF_HEROES,
      new int[]{ItemID.SPLITBARK_LEGS, ItemID.DRAGON_BOOTS, ItemID.RUNE_LONGSWORD},
      ItemRequirements.item(ItemID.SPLITBARK_LEGS),
      ItemRequirements.any(
          "Dragon boots",
          ItemRequirements.item(ItemID.DRAGON_BOOTS),
          ItemRequirements.item(ItemID.DRAGON_BOOTS_G),
          ItemRequirements.item(ItemID.PRIMORDIAL_BOOTS)),
      ItemRequirements.item(ItemID.RUNE_LONGSWORD)),
  MOUNTAIN_CAMP_GOAT_ENCLOSURE(
      "Mountain Camp",
      "Mountain Camp goat enclosure",
      STASHUnit.MOUNTAIN_CAMP_GOAT_ENCLOSURE,
      new int[]{ItemID.RUNE_FULL_HELM, ItemID.BLUE_DHIDE_CHAPS, ItemID.FIRE_BATTLESTAFF},
      ItemRequirements.item(ItemID.RUNE_FULL_HELM),
      ItemRequirements.item(ItemID.BLUE_DHIDE_CHAPS),
      ItemRequirements.item(ItemID.FIRE_BATTLESTAFF)),
  ROAD_JUNCTION_SOUTH_OF_SINCLAIR_MANSION(
      "Sinclair Mansion",
      "Road junction south of Sinclair Mansion",
      STASHUnit.ROAD_JUNCTION_SOUTH_OF_SINCLAIR_MANSION,
      new int[]{ItemID.LEATHER_COWL, ItemID.BLUE_WIZARD_ROBE, ItemID.IRON_SCIMITAR},
      ItemRequirements.item(ItemID.LEATHER_COWL),
      ItemRequirements.item(ItemID.BLUE_WIZARD_ROBE),
      ItemRequirements.item(ItemID.IRON_SCIMITAR)),
  NEAR_THE_GEM_STALL_IN_ARDOUGNE_MARKET(
      "Ardougne",
      "Near the gem stall in Ardougne Market",
      STASHUnit.NEAR_THE_GEM_STALL_IN_ARDOUGNE_MARKET,
      new int[]{ItemID.CASTLE_WARS_BRACELET3, ItemID.DRAGONSTONE_AMULET, ItemID.RING_OF_FORGING},
      ItemRequirements.any(
          "Castle wars bracelet",
          ItemRequirements.range(ItemID.CASTLE_WARS_BRACELET3, ItemID.CASTLE_WARS_BRACELET1)),
      ItemRequirements.item(ItemID.DRAGONSTONE_AMULET),
      ItemRequirements.item(ItemID.RING_OF_FORGING)),
  LIMESTONE_MINE(
      "Limestone Mine",
      "Limestone mine",
      STASHUnit.LIMESTONE_MINE,
      new int[]{ItemID.BRONZE_PLATELEGS, ItemID.STEEL_PICKAXE, ItemID.STEEL_MED_HELM},
      ItemRequirements.item(ItemID.BRONZE_PLATELEGS),
      ItemRequirements.item(ItemID.STEEL_PICKAXE),
      ItemRequirements.item(ItemID.STEEL_MED_HELM)),
  MAUSOLEUM_OFF_THE_MORYTANIA_COAST(
      "Morytania mausoleum",
      "Mausoleum off the Morytania coast",
      STASHUnit.MAUSOLEUM_OFF_THE_MORYTANIA_COAST,
      new int[]{ItemID.MITHRIL_PLATESKIRT, ItemID.MAPLE_LONGBOW},
      ItemRequirements.item(ItemID.MITHRIL_PLATESKIRT),
      ItemRequirements.item(ItemID.MAPLE_LONGBOW)),
  VOLCANO_IN_THE_NORTHEASTERN_WILDERNESS(
      "Wilderness volcano",
      "Volcano in the north-eastern Wilderness",
      STASHUnit.VOLCANO_IN_THE_NORTHEASTERN_WILDERNESS,
      new int[]{ItemID.RED_HEADBAND, ItemID.ANCIENT_CROZIER},
      ItemRequirements.any(
          "Any headband",
          ItemRequirements.range(ItemID.RED_HEADBAND, ItemID.BROWN_HEADBAND),
          ItemRequirements.range(ItemID.WHITE_HEADBAND, ItemID.GREEN_HEADBAND)),
      ItemRequirements.any(
          "Any crozier",
          ItemRequirements.item(ItemID.ANCIENT_CROZIER),
          ItemRequirements.item(ItemID.ARMADYL_CROZIER),
          ItemRequirements.item(ItemID.BANDOS_CROZIER),
          ItemRequirements.range(ItemID.SARADOMIN_CROZIER, ItemID.ZAMORAK_CROZIER))),
  GNOME_GLIDER_ON_WHITE_WOLF_MOUNTAIN(
      "White Wolf Mountain",
      "Gnome Glider on White Wolf Mountain",
      STASHUnit.GNOME_GLIDER_ON_WHITE_WOLF_MOUNTAIN,
      new int[]{ItemID.MITHRIL_PLATELEGS, ItemID.RING_OF_LIFE, ItemID.RUNE_AXE},
      ItemRequirements.item(ItemID.MITHRIL_PLATELEGS),
      ItemRequirements.item(ItemID.RING_OF_LIFE),
      ItemRequirements.item(ItemID.RUNE_AXE)),
  SOUTHEAST_CORNER_OF_LAVA_DRAGON_ISLE(
      "Lava dragon isle",
      "South-east corner of Lava Dragon Isle",
      STASHUnit.SOUTHEAST_CORNER_OF_LAVA_DRAGON_ISLE,
      new int[]{
          ItemID.DRAGON_MED_HELM, ItemID.TOKTZKETXIL, ItemID.BRINE_SABRE, ItemID.RUNE_PLATEBODY,
          ItemID.AMULET_OF_GLORY
      },
      ItemRequirements.item(ItemID.DRAGON_MED_HELM),
      ItemRequirements.item(ItemID.TOKTZKETXIL),
      ItemRequirements.item(ItemID.BRINE_SABRE),
      ItemRequirements.item(ItemID.RUNE_PLATEBODY),
      ItemRequirements.any(
          "Uncharged Amulet of glory", ItemRequirements.item(ItemID.AMULET_OF_GLORY))),
  HALFWAY_DOWN_TROLLWEISS_MOUNTAIN(
      "Trollweiss mountain",
      "Half-way down Trollweiss Mountain",
      STASHUnit.HALFWAY_DOWN_TROLLWEISS_MOUNTAIN,
      new int[]{
          ItemID.BLUE_DHIDE_VAMBRACES, ItemID.DRAGON_SPEAR, ItemID.RUNE_PLATESKIRT, ItemID.SLED_4084
      },
      ItemRequirements.item(ItemID.BLUE_DHIDE_VAMBRACES),
      ItemRequirements.item(ItemID.DRAGON_SPEAR),
      ItemRequirements.item(ItemID.RUNE_PLATESKIRT),
      ItemRequirements.item(ItemID.SLED_4084)),
  WARRIORS_GUILD_BANK_29047(
      "Warriors' guild",
      "Warriors' Guild bank (master)",
      STASHUnit.WARRIORS_GUILD_BANK_29047,
      new int[]{ItemID.DRAGON_BATTLEAXE, ItemID.DRAGON_DEFENDER, ItemID.SLAYER_HELMET},
      ItemRequirements.item(ItemID.DRAGON_BATTLEAXE),
      ItemRequirements.any(
          "Dragon defender or Avernic defender",
          ItemRequirements.item(ItemID.DRAGON_DEFENDER),
          ItemRequirements.item(ItemID.DRAGON_DEFENDER_T),
          ItemRequirements.item(ItemID.DRAGON_DEFENDER_L),
          ItemRequirements.item(ItemID.AVERNIC_DEFENDER),
          ItemRequirements.item(ItemID.AVERNIC_DEFENDER_L)),
      ItemRequirements.any(
          "Any slayer helmet",
          ItemRequirements.item(ItemID.SLAYER_HELMET),
          ItemRequirements.item(ItemID.BLACK_SLAYER_HELMET),
          ItemRequirements.item(ItemID.GREEN_SLAYER_HELMET),
          ItemRequirements.item(ItemID.PURPLE_SLAYER_HELMET),
          ItemRequirements.item(ItemID.RED_SLAYER_HELMET),
          ItemRequirements.item(ItemID.TURQUOISE_SLAYER_HELMET),
          ItemRequirements.item(ItemID.HYDRA_SLAYER_HELMET),
          ItemRequirements.item(ItemID.TWISTED_SLAYER_HELMET),
          ItemRequirements.item(ItemID.TZTOK_SLAYER_HELMET),
          ItemRequirements.item(ItemID.VAMPYRIC_SLAYER_HELMET),
          ItemRequirements.item(ItemID.TZKAL_SLAYER_HELMET),
          ItemRequirements.item(ItemID.SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.BLACK_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.GREEN_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.PURPLE_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.RED_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.TURQUOISE_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.HYDRA_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.TWISTED_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.TZTOK_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.VAMPYRIC_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.TZKAL_SLAYER_HELMET_I),
          ItemRequirements.item(ItemID.SLAYER_HELMET_I_25177),
          ItemRequirements.item(ItemID.BLACK_SLAYER_HELMET_I_25179),
          ItemRequirements.item(ItemID.GREEN_SLAYER_HELMET_I_25181),
          ItemRequirements.item(ItemID.RED_SLAYER_HELMET_I_25183),
          ItemRequirements.item(ItemID.PURPLE_SLAYER_HELMET_I_25185),
          ItemRequirements.item(ItemID.TURQUOISE_SLAYER_HELMET_I_25187),
          ItemRequirements.item(ItemID.HYDRA_SLAYER_HELMET_I_25189),
          ItemRequirements.item(ItemID.TWISTED_SLAYER_HELMET_I_25191),
          ItemRequirements.item(ItemID.TZTOK_SLAYER_HELMET_I_25902),
          ItemRequirements.item(ItemID.VAMPYRIC_SLAYER_HELMET_I_25908),
          ItemRequirements.item(ItemID.TZKAL_SLAYER_HELMET_I_25914))),
  NEAR_THE_PARROTS_IN_ARDOUGNE_ZOO(
      "Ardougne Zoo",
      "Near the parrots in Ardougne Zoo",
      STASHUnit.NEAR_THE_PARROTS_IN_ARDOUGNE_ZOO,
      new int[]{ItemID.STUDDED_BODY, ItemID.BRONZE_PLATELEGS, ItemID.STAFF},
      ItemRequirements.item(ItemID.STUDDED_BODY),
      ItemRequirements.item(ItemID.BRONZE_PLATELEGS),
      ItemRequirements.item(ItemID.STAFF)),
  OUTSIDE_KEEP_LE_FAYE(
      "Keep Le Faye",
      "Outside Keep Le Faye",
      STASHUnit.OUTSIDE_KEEP_LE_FAYE,
      new int[]{ItemID.COIF, ItemID.IRON_PLATEBODY, ItemID.LEATHER_GLOVES},
      ItemRequirements.item(ItemID.COIF),
      ItemRequirements.item(ItemID.IRON_PLATEBODY),
      ItemRequirements.item(ItemID.LEATHER_GLOVES)),
  FISHING_GUILD_BANK(
      "Fishing Guild",
      "Fishing Guild bank",
      STASHUnit.FISHING_GUILD_BANK,
      new int[]{ItemID.ELEMENTAL_SHIELD, ItemID.BLUE_DHIDE_CHAPS, ItemID.RUNE_WARHAMMER},
      ItemRequirements.item(ItemID.ELEMENTAL_SHIELD),
      ItemRequirements.item(ItemID.BLUE_DHIDE_CHAPS),
      ItemRequirements.item(ItemID.RUNE_WARHAMMER)),
  WEST_SIDE_OF_THE_KARAMJA_BANANA_PLANTATION(
      "Karamja",
      "West side of the Karamja banana plantation",
      STASHUnit.WEST_SIDE_OF_THE_KARAMJA_BANANA_PLANTATION,
      new int[]{ItemID.DIAMOND_RING, ItemID.AMULET_OF_POWER},
      ItemRequirements.item(ItemID.DIAMOND_RING),
      ItemRequirements.item(ItemID.AMULET_OF_POWER)),
  WARRIORS_GUILD_BANK(
      "Warriors' guild",
      "Warriors' Guild bank",
      STASHUnit.WARRIORS_GUILD_BANK,
      new int[]{ItemID.BLACK_SALAMANDER},
      ItemRequirements.item(ItemID.BLACK_SALAMANDER)),
  HOSIDIUS_MESS(
      "Hosidius mess hall",
      "Hosidius Mess",
      STASHUnit.HOSIDIUS_MESS,
      new int[]{ItemID.RUNE_HALBERD, ItemID.RUNE_PLATEBODY, ItemID.AMULET_OF_STRENGTH},
      ItemRequirements.item(ItemID.RUNE_HALBERD),
      ItemRequirements.item(ItemID.RUNE_PLATEBODY),
      ItemRequirements.item(ItemID.AMULET_OF_STRENGTH)),
  RIMMINGTON_MINE(
      "Rimmington mine",
      "Rimmington mine",
      STASHUnit.RIMMINGTON_MINE,
      new int[]{ItemID.GOLD_NECKLACE, ItemID.GOLD_RING, ItemID.BRONZE_SPEAR},
      ItemRequirements.item(ItemID.GOLD_NECKLACE),
      ItemRequirements.item(ItemID.GOLD_RING),
      ItemRequirements.item(ItemID.BRONZE_SPEAR)),
  OUTSIDE_CATHERBY_BANK(
      "Catherby",
      "Outside Catherby bank",
      STASHUnit.OUTSIDE_CATHERBY_BANK,
      new int[]{ItemID.MAPLE_LONGBOW, ItemID.GREEN_DHIDE_CHAPS, ItemID.IRON_MED_HELM},
      ItemRequirements.item(ItemID.MAPLE_LONGBOW),
      ItemRequirements.item(ItemID.GREEN_DHIDE_CHAPS),
      ItemRequirements.item(ItemID.IRON_MED_HELM)),
  CHAOS_TEMPLE_IN_THE_SOUTHEASTERN_WILDERNESS(
      "Chaos temple",
      "Chaos Temple in the south-eastern Wilderness",
      STASHUnit.EAST_OF_THE_LEVEL_19_WILDERNESS_OBELISK,
      new int[]{ItemID.RUNE_PLATELEGS, ItemID.IRON_PLATEBODY, ItemID.BLUE_DHIDE_VAMBRACES},
      ItemRequirements.item(ItemID.RUNE_PLATELEGS),
      ItemRequirements.item(ItemID.IRON_PLATEBODY),
      ItemRequirements.item(ItemID.BLUE_DHIDE_VAMBRACES)),
  SHAYZIEN_WAR_TENT(
      "Shayzien war tent",
      "Shayzien War Tent",
      STASHUnit.SHAYZIEN_WAR_TENT,
      new int[]{ItemID.MYSTIC_ROBE_BOTTOM, ItemID.RUNE_KITESHIELD, ItemID.BOBS_RED_SHIRT},
      ItemRequirements.item(ItemID.MYSTIC_ROBE_BOTTOM),
      ItemRequirements.item(ItemID.RUNE_KITESHIELD),
      ItemRequirements.range(ItemID.BOBS_RED_SHIRT, ItemID.BOBS_PURPLE_SHIRT)),
  CENTRE_OF_THE_CATACOMBS_OF_KOUREND(
      "Kourend catacombs",
      "Centre of the Catacombs of Kourend",
      STASHUnit.CENTRE_OF_THE_CATACOMBS_OF_KOUREND,
      new int[]{ItemID.ARCLIGHT, ItemID.AMULET_OF_THE_DAMNED},
      ItemRequirements.item(ItemID.ARCLIGHT),
      ItemRequirements.any(
          "Amulet of the damned",
          ItemRequirements.item(ItemID.AMULET_OF_THE_DAMNED),
          ItemRequirements.item(ItemID.AMULET_OF_THE_DAMNED_FULL))),
  ROAD_JUNCTION_NORTH_OF_RIMMINGTON(
      "Rimmington",
      "Road junction north of Rimmington",
      STASHUnit.ROAD_JUNCTION_NORTH_OF_RIMMINGTON,
      new int[]{ItemID.GREEN_HAT, ItemID.CREAM_ROBE_TOP, ItemID.LEATHER_CHAPS},
      ItemRequirements.item(ItemID.GREEN_HAT),
      ItemRequirements.item(ItemID.CREAM_ROBE_TOP),
      ItemRequirements.item(ItemID.LEATHER_CHAPS)),
  DRAYNOR_MANOR_BY_THE_FOUNTAIN(
      "Draynor Manor",
      "Draynor Manor by the fountain",
      STASHUnit.DRAYNOR_MANOR_BY_THE_FOUNTAIN,
      new int[]{ItemID.IRON_PLATEBODY, ItemID.STUDDED_CHAPS, ItemID.BRONZE_FULL_HELM},
      ItemRequirements.item(ItemID.IRON_PLATEBODY),
      ItemRequirements.item(ItemID.STUDDED_CHAPS),
      ItemRequirements.item(ItemID.BRONZE_FULL_HELM)),
  SOUL_ALTAR(
      "Soul altar",
      "Soul Altar",
      STASHUnit.SOUL_ALTAR,
      new int[]{ItemID.DRAGON_PICKAXE, ItemID.HELM_OF_NEITIZNOT, ItemID.RUNE_BOOTS},
      ItemRequirements.any(
          "Dragon or Crystal pickaxe",
          ItemRequirements.item(ItemID.DRAGON_PICKAXE),
          ItemRequirements.item(ItemID.DRAGON_PICKAXE_12797),
          ItemRequirements.item(ItemID.INFERNAL_PICKAXE),
          ItemRequirements.item(ItemID.INFERNAL_PICKAXE_UNCHARGED),
          ItemRequirements.item(ItemID.DRAGON_PICKAXE_OR),
          ItemRequirements.item(ItemID.DRAGON_PICKAXE_OR_25376),
          ItemRequirements.item(ItemID.CRYSTAL_PICKAXE),
          ItemRequirements.item(ItemID.CRYSTAL_PICKAXE_INACTIVE),
          ItemRequirements.item(ItemID.INFERNAL_PICKAXE_OR),
          ItemRequirements.item(ItemID.INFERNAL_PICKAXE_UNCHARGED_25369)),
      ItemRequirements.item(ItemID.HELM_OF_NEITIZNOT),
      ItemRequirements.item(ItemID.RUNE_BOOTS)),
  OUTSIDE_VARROCK_PALACE_COURTYARD(
      "Varrock Castle",
      "Outside Varrock Palace courtyard",
      STASHUnit.OUTSIDE_VARROCK_PALACE_COURTYARD,
      new int[]{ItemID.BLACK_AXE, ItemID.COIF, ItemID.RUBY_RING},
      ItemRequirements.item(ItemID.BLACK_AXE),
      ItemRequirements.item(ItemID.COIF),
      ItemRequirements.item(ItemID.RUBY_RING)),
  CHAPEL_IN_WEST_ARDOUGNE(
      "West Ardougne Church",
      "Chapel in West Ardougne",
      STASHUnit.CHAPEL_IN_WEST_ARDOUGNE,
      new int[]{ItemID.DRAGON_SPEAR, ItemID.RED_DHIDE_CHAPS},
      ItemRequirements.item(ItemID.DRAGON_SPEAR),
      ItemRequirements.item(ItemID.RED_DHIDE_CHAPS)),
  EAST_OF_THE_BARBARIAN_VILLAGE_BRIDGE(
      "Barbarian Village",
      "East of the Barbarian Village bridge",
      STASHUnit.EAST_OF_THE_BARBARIAN_VILLAGE_BRIDGE,
      new int[]{ItemID.PURPLE_GLOVES, ItemID.STEEL_KITESHIELD, ItemID.MITHRIL_FULL_HELM},
      ItemRequirements.item(ItemID.PURPLE_GLOVES),
      ItemRequirements.item(ItemID.STEEL_KITESHIELD),
      ItemRequirements.item(ItemID.MITHRIL_FULL_HELM)),
  NORTHWESTERN_CORNER_OF_THE_ENCHANTED_VALLEY(
      "Enchanted Valley (BKQ)",
      "North-western corner of the Enchanted Valley",
      STASHUnit.NORTHWESTERN_CORNER_OF_THE_ENCHANTED_VALLEY,
      new int[]{ItemID.DRAGON_AXE},
      ItemRequirements.any(
          "Dragon or Crystal axe",
          ItemRequirements.item(ItemID.DRAGON_AXE),
          ItemRequirements.item(ItemID.DRAGON_AXE_OR),
          ItemRequirements.item(ItemID.CRYSTAL_AXE),
          ItemRequirements.item(ItemID.CRYSTAL_AXE_INACTIVE),
          ItemRequirements.item(ItemID.INFERNAL_AXE),
          ItemRequirements.item(ItemID.INFERNAL_AXE_UNCHARGED),
          ItemRequirements.item(ItemID.INFERNAL_AXE_OR),
          ItemRequirements.item(ItemID.INFERNAL_AXE_UNCHARGED_25371))),
  WHEAT_FIELD_NEAR_THE_LUMBRIDGE_WINDMILL(
      "Lumbridge mill",
      "Wheat field near the Lumbridge windmill",
      STASHUnit.WHEAT_FIELD_NEAR_THE_LUMBRIDGE_WINDMILL,
      new int[]{ItemID.BLUE_ROBE_TOP, ItemID.TURQUOISE_ROBE_BOTTOMS, ItemID.OAK_SHORTBOW},
      ItemRequirements.item(ItemID.BLUE_ROBE_TOP),
      ItemRequirements.item(ItemID.TURQUOISE_ROBE_BOTTOMS),
      ItemRequirements.item(ItemID.OAK_SHORTBOW)),
  OBSERVATORY(
      "Observatory",
      "Observatory",
      STASHUnit.OBSERVATORY,
      new int[]{ItemID.MITHRIL_CHAINBODY, ItemID.GREEN_DHIDE_CHAPS, ItemID.RUBY_AMULET},
      ItemRequirements.item(ItemID.MITHRIL_CHAINBODY),
      ItemRequirements.item(ItemID.GREEN_DHIDE_CHAPS),
      ItemRequirements.item(ItemID.RUBY_AMULET)),
  NEAR_THE_SAWMILL_OPERATORS_BOOTH(
      "Lumber Yard",
      "Near the Sawmill Operator's booth",
      STASHUnit.NEAR_THE_SAWMILL_OPERATORS_BOOTH,
      new int[]{ItemID.HARDLEATHER_BODY, ItemID.LEATHER_CHAPS, ItemID.BRONZE_AXE},
      ItemRequirements.item(ItemID.HARDLEATHER_BODY),
      ItemRequirements.item(ItemID.LEATHER_CHAPS),
      ItemRequirements.item(ItemID.BRONZE_AXE)),
  NEAR_HERQUINS_SHOP_IN_FALADOR(
      "Falador",
      "Near Herquin's shop in Falador",
      STASHUnit.NEAR_HERQUINS_SHOP_IN_FALADOR,
      new int[]{ItemID.MITHRIL_PICKAXE, ItemID.BLACK_PLATEBODY, ItemID.IRON_KITESHIELD},
      ItemRequirements.item(ItemID.MITHRIL_PICKAXE),
      ItemRequirements.item(ItemID.BLACK_PLATEBODY),
      ItemRequirements.item(ItemID.IRON_KITESHIELD)),
  MUDSKIPPER_POINT(
      "Mudskipper Point",
      "Mudskipper Point",
      STASHUnit.MUDSKIPPER_POINT,
      new int[]{ItemID.BLACK_CAPE, ItemID.LEATHER_CHAPS, ItemID.STEEL_MACE},
      ItemRequirements.item(ItemID.BLACK_CAPE),
      ItemRequirements.item(ItemID.LEATHER_CHAPS),
      ItemRequirements.item(ItemID.STEEL_MACE)),
  NORTHERN_WALL_OF_CASTLE_DRAKAN(
      "Castle Drakan",
      "Northern wall of Castle Drakan",
      STASHUnit.NORTHERN_WALL_OF_CASTLE_DRAKAN,
      new int[]{ItemID.DRAGON_SQ_SHIELD, ItemID.SPLITBARK_BODY, ItemID.RED_BOATER},
      ItemRequirements.any(
          "Dragon sq shield",
          ItemRequirements.item(ItemID.DRAGON_SQ_SHIELD),
          ItemRequirements.item(ItemID.DRAGON_SQ_SHIELD_G)),
      ItemRequirements.item(ItemID.SPLITBARK_BODY),
      ItemRequirements.any(
          "Any boater",
          ItemRequirements.item(ItemID.RED_BOATER),
          ItemRequirements.item(ItemID.ORANGE_BOATER),
          ItemRequirements.item(ItemID.GREEN_BOATER),
          ItemRequirements.item(ItemID.BLUE_BOATER),
          ItemRequirements.item(ItemID.BLACK_BOATER),
          ItemRequirements.item(ItemID.PINK_BOATER),
          ItemRequirements.item(ItemID.PURPLE_BOATER),
          ItemRequirements.item(ItemID.WHITE_BOATER))),
  SEVENTH_CHAMBER_OF_JALSAVRAH(
      "Pyramid Plunder",
      "7th Chamber of Jalsavrah",
      STASHUnit._7TH_CHAMBER_OF_JALSAVRAH,
      new int[]{
          ItemID.PHARAOHS_SCEPTRE,
          ItemID.MENAPHITE_PURPLE_HAT,
          ItemID.MENAPHITE_PURPLE_TOP,
          ItemID.MENAPHITE_PURPLE_ROBE
      },
      ItemRequirements.any(
          "Pharaoh's sceptre",
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9045),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9046),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9047),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9048),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9049),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9050),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_9051),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_13074),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_13075),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_13077),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_13078),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_16176),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_21445),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_21446),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_26948),
          ItemRequirements.item(ItemID.PHARAOHS_SCEPTRE_26950)),
      ItemRequirements.any(
          "Full set of menaphite robes",
          ItemRequirements.all(
              ItemRequirements.item(ItemID.MENAPHITE_PURPLE_HAT),
              ItemRequirements.item(ItemID.MENAPHITE_PURPLE_TOP),
              ItemRequirements.range(ItemID.MENAPHITE_PURPLE_ROBE, ItemID.MENAPHITE_PURPLE_KILT)),
          ItemRequirements.all(
              ItemRequirements.item(ItemID.MENAPHITE_RED_HAT),
              ItemRequirements.item(ItemID.MENAPHITE_RED_TOP),
              ItemRequirements.range(ItemID.MENAPHITE_RED_ROBE, ItemID.MENAPHITE_RED_KILT)))),
  VARROCK_PALACE_LIBRARY(
      "Varrock Castle",
      "Varrock Palace Library",
      STASHUnit.VARROCK_PALACE_LIBRARY,
      new int[]{ItemID.GREEN_ROBE_TOP, ItemID.HAM_ROBE, ItemID.IRON_WARHAMMER},
      ItemRequirements.item(ItemID.GREEN_ROBE_TOP),
      ItemRequirements.item(ItemID.HAM_ROBE),
      ItemRequirements.item(ItemID.IRON_WARHAMMER)),
  DRAYNOR_VILLAGE_MARKET(
      "Draynor",
      "Draynor Village market",
      STASHUnit.DRAYNOR_VILLAGE_MARKET,
      new int[]{ItemID.STUDDED_CHAPS, ItemID.IRON_KITESHIELD, ItemID.STEEL_LONGSWORD},
      ItemRequirements.item(ItemID.STUDDED_CHAPS),
      ItemRequirements.item(ItemID.IRON_KITESHIELD),
      ItemRequirements.item(ItemID.STEEL_LONGSWORD)),
  CASTLE_WARS_BANK(
      "Castle Wars",
      "Castle Wars bank",
      STASHUnit.CASTLE_WARS_BANK,
      new int[]{ItemID.RUBY_AMULET, ItemID.MITHRIL_SCIMITAR, ItemID.TEAM1_CAPE},
      ItemRequirements.item(ItemID.RUBY_AMULET),
      ItemRequirements.item(ItemID.MITHRIL_SCIMITAR),
      ItemRequirements.range(ItemID.TEAM1_CAPE, ItemID.TEAM50_CAPE)),
  NOTERAZZOS_SHOP_IN_THE_WILDERNESS(
      "Rogues general store",
      "Noterazzo's shop in the Wilderness",
      STASHUnit.NOTERAZZOS_SHOP_IN_THE_WILDERNESS,
      new int[]{ItemID.ADAMANT_SQ_SHIELD, ItemID.BLUE_DHIDE_VAMBRACES, ItemID.RUNE_PICKAXE},
      ItemRequirements.item(ItemID.ADAMANT_SQ_SHIELD),
      ItemRequirements.item(ItemID.BLUE_DHIDE_VAMBRACES),
      ItemRequirements.item(ItemID.RUNE_PICKAXE)),
  ON_TOP_OF_TROLLHEIM_MOUNTAIN(
      "Trollheim Mountain",
      "On top of Trollheim Mountain",
      STASHUnit.ON_TOP_OF_TROLLHEIM_MOUNTAIN,
      new int[]{ItemID.LAVA_BATTLESTAFF, ItemID.BLACK_DHIDE_VAMBRACES, ItemID.MIND_SHIELD},
      ItemRequirements.any(
          "Lava battlestaff",
          ItemRequirements.item(ItemID.LAVA_BATTLESTAFF),
          ItemRequirements.item(ItemID.LAVA_BATTLESTAFF_21198)),
      ItemRequirements.item(ItemID.BLACK_DHIDE_VAMBRACES),
      ItemRequirements.item(ItemID.MIND_SHIELD)),
  ENTRANCE_OF_THE_ARCEUUS_LIBRARY(
      "Arceuus library",
      "Entrance of the Arceuus library",
      STASHUnit.ENTRANCE_OF_THE_ARCEUUS_LIBRARY,
      new int[]{ItemID.BLUE_DHIDE_VAMBRACES, ItemID.ADAMANT_BOOTS, ItemID.ADAMANT_DAGGER},
      ItemRequirements.item(ItemID.BLUE_DHIDE_VAMBRACES),
      ItemRequirements.item(ItemID.ADAMANT_BOOTS),
      ItemRequirements.item(ItemID.ADAMANT_DAGGER)),
  TOP_FLOOR_OF_THE_YANILLE_WATCHTOWER(
      "Yanille Watchtower",
      "Top floor of the Yanille Watchtower",
      STASHUnit.TOP_FLOOR_OF_THE_YANILLE_WATCHTOWER,
      new int[]{
          ItemID.DRAGON_PLATESKIRT,
          ItemID.CLIMBING_BOOTS,
          ItemID.DRAGON_CHAINBODY_3140,
          ItemID.BULLROARER
      },
      ItemRequirements.any(
          "Dragon plateskirt",
          ItemRequirements.item(ItemID.DRAGON_PLATESKIRT),
          ItemRequirements.item(ItemID.DRAGON_PLATESKIRT_G)),
      ItemRequirements.item(ItemID.CLIMBING_BOOTS),
      ItemRequirements.any(
          "Dragon chainbody",
          ItemRequirements.item(ItemID.DRAGON_CHAINBODY_3140),
          ItemRequirements.item(ItemID.DRAGON_CHAINBODY_G)),
      ItemRequirements.item(ItemID.BULLROARER)),
  GYPSY_TENT_ENTRANCE(
      "Varrock",
      "Gypsy Aris' tent",
      STASHUnit.GYPSY_TENT_ENTRANCE,
      new int[]{ItemID.GOLD_RING, ItemID.GOLD_NECKLACE},
      ItemRequirements.item(ItemID.GOLD_RING),
      ItemRequirements.item(ItemID.GOLD_NECKLACE)),
  FINE_CLOTHES_ENTRANCE(
      "Varrock",
      "Iffie Nitter in Varrock",
      STASHUnit.FINE_CLOTHES_ENTRANCE,
      new int[]{ItemID.CHEFS_HAT, ItemID.RED_CAPE},
      ItemRequirements.item(ItemID.CHEFS_HAT),
      ItemRequirements.item(ItemID.RED_CAPE)),
  BOB_AXES_ENTRANCE(
      "Lumbridge",
      "Bob's Brilliant Axes in Lumbridge",
      STASHUnit.BOB_AXES_ENTRANCE,
      new int[]{ItemID.BRONZE_AXE, ItemID.LEATHER_BOOTS},
      ItemRequirements.item(ItemID.BRONZE_AXE),
      ItemRequirements.item(ItemID.LEATHER_BOOTS)),
  CHARCOAL_BURNERS(
      "Charcoal Burners",
      "Near the Charcoal Burners",
      STASHUnit.CHARCOAL_BURNERS,
      new int[]{ItemID.FARMERS_STRAWHAT, ItemID.SHAYZIEN_BODY_5, ItemID.PYROMANCER_ROBE},
      ItemRequirements.any(
          "Farmer's strawhat",
          ItemRequirements.item(ItemID.FARMERS_STRAWHAT),
          ItemRequirements.item(ItemID.FARMERS_STRAWHAT_13647)),
      ItemRequirements.item(ItemID.SHAYZIEN_BODY_5),
      ItemRequirements.item(ItemID.PYROMANCER_ROBE));

  private final String locationName;
  private final String chartText;
  private final STASHUnit stashUnitData;
  private final int[] defaultItemIds;
  private final ItemRequirement[] itemRequirements;

  StashUnit(
      String locationName,
      String chartText,
      STASHUnit stashUnitData,
      @Nonnull int[] defaultItemIds,
      @Nonnull ItemRequirement... itemRequirements) {
    this.locationName = locationName;
    this.stashUnitData = stashUnitData;
    this.chartText = chartText;
    this.defaultItemIds = defaultItemIds;
    this.itemRequirements = itemRequirements;
  }
}
